---
sidebar_position: 8
description: "Restate's retry strategy and how to manage it from the SDK."
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

# Error handling

Restate takes care of retries of failed invocations. 
It does this for all kinds of errors, such as transient network errors and errors thrown inside handlers. 
By default, Restate does infinite retries with an exponential backoff strategy.

For situations where you do not want the invocation to be retried, but instead you want the error message
to be propagated back to the caller, you can use a terminal error.

<Tabs groupId="sdk" queryString>
<TabItem value="ts" label="TypeScript">

```typescript
import { TerminalError, ErrorCodes } from "@restatedev/restate-sdk";

// Inside your handler throw terminal errors via:
throw new TerminalError("Something went wrong.", { errorCode: ErrorCodes.INTERNAL })
```

The `errorCode` is optional. `errorCode` is a [gRPC status code](https://grpc.github.io/grpc/core/md_doc_statuscodes.html).
You can throw a terminal error anywhere in your handler.
Restate will propagate the error code and message back to the caller and will consider this invocation to be finished.

If a terminal error is returned to an HTTP client of the ingress, it will be converted into an appropriate HTTP status code, which
is documented in the TSDoc of the ErrorCodes enum.

:::note Errors during side effect execution

Throwing errors inside a side effect has the same semantics as anywhere else in your handler code.
By default, Restate infinitely retries the invocation, and therefore the side effect.
Errors that should not be retried, should be thrown as terminal errors, as described earlier.

Invocation retries are triggered by Restate, not by the SDKs.
For some use cases, you may want to do the side effect retries from within the invocation,
because this is faster and more efficient in certain scenarios (e.g. you have a connection set up to an external system or database).
Have a look at the [side effect documentation](/develop/sdk/side-effects#retrying-on-failure)
on how to set this up.
:::

</TabItem>
<TabItem value="java" label="Java">


You can throw a terminal exception via `dev.restate.sdk.core.TerminalException` and supply it with a `dev.restate.sdk.core.TerminalException.Code` and a message:

```java
import dev.restate.sdk.core.TerminalException;

// Inside your handler throw terminal errors with a code and message as follows:
throw new TerminalException(Code.UNKNOWN, "Something went wrong");
```

:::note Errors during side effect execution
Throwing errors inside a side effect has the same semantics as anywhere else in your handler code.
By default, Restate infinitely retries the invocation, and therefore the side effect.
Errors that should not be retried, should be thrown as terminal errors, as described earlier.
Invocation retries are triggered by Restate, not by the SDKs.
:::

You can catch terminal exceptions. For example, you can catch the terminal exception that comes out of a call to another service (`ctx.call(...).await()`) , and build your control flow around it.

</TabItem>
</Tabs>

You can throw a terminal error anywhere in your handler.
Restate will propagate the error code and message back to the caller and will consider this invocation to be finished. 

